version: "3.3"
services:
  galera-web:
    build: ./
    container_name: galera-web
    depends_on:
      - galera-db
    entrypoint: ["make", "wait-for-db", "run-prod"]
    environment:
      DATABASE_URL: "postgresql://galera:galera@galera-db:5432/galera"
      PORT: 80
    image: galera-web
    ports:
      - "8888:80"
  galera-db:
    container_name: galera-db
    environment:
      POSTGRES_USER: galera
      POSTGRES_PASSWORD: galera
      POSTGRES_DB: galera
    image: postgres:13.3-alpine
    ports:
      - "5555:5432"
    restart: always
    volumes:
      - galera-volume:/var/lib/postgresql/data
  galera-dba:
    container_name: galera-dba
    image: adminer
    restart: always
    ports:
      - 5556:8080
    volumes:
      - galera-volume:/var/lib/postgresql/data
volumes:
  galera-volume:
    name: galera-volume
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=100m
